### ISSUE TITLE
Leaves a backslash with Haskell Syntax Highlighting module

### ISSUE THREAD

**Issue by scott-fleischman** [freebroccolo/vscode-input-assist#1] opened 2016-11-11 00:04 UTC
This works great in reason files, thanks for adding it!

However, in Haskell files using the [Haskell Syntax Highlighting](https://marketplace.visualstudio.com/items?itemName=justusadam.language-haskell) extension (not sure if that's related or not), it leaves the backslash in the input when I type something like `\Ga` -> `\α` instead of `α`.

Do you know if there's a setting that might affect that or if the extensions are incompatible, or if there's a way this extension could work that wouldn't affect that?

**Comment by freebroccolo** [comment] 2016-11-11 00:28
Yeah there are currently some issues using the input method with arbitrary extensions. The problem is that both the completion triggering and the text edit that does the symbol replacement in the buffer are computed in part by the [wordPattern](https://github.com/freebroccolo/vscode-reasonml/blob/master/src/extension.ts#L90) for the language.

For the reason and agda extensions I have modified the `wordPattern` (as you can see above) to include things like `\…`. The reason this is necessary is because by default if you are completing and you type a non-word character (say `*` or some other non-alpha numeric), the suggestion widget will close. This is part of the default completion provider behavior (which might be possible to override, not sure yet). So without that extended `wordPattern`, typing things like `\=>n` wouldn't work.

What happens in some languages when the `\` is not being replaced is that the extension searched backward for the word boundary when it was ready to do the buffer replacement but stopped too early (not including the `\` as it should). In an earlier version of the plugin I had some workarounds in place that would try to do an additional text edit to replace the leading `\` anyway but it got removed when I was trying to fix some other stuff.

I can reimplement that functionality as a fallback but there's still the larger issue of how to work around not having `\…` included in the `wordPattern` for some languages. What this would mean in practice is that some of the completions (those that include non-alphanum characters) for a language without this extended `wordPattern` still would not be easy to type without the suggestion widget closing. 

I believe there are a few different ways to work around the `wordPattern` limitation in principle but I need to experiment some more to find the right solution. There is one approach I am almost sure will work but it might cause a little bit of flickering in the widget. Maybe it's not a big deal though.

I'll try to go ahead and reimplemented the more limited workaround in the meantime.

**Comment by freebroccolo** [comment] 2016-11-11 00:40
I should add that if you are willing to fork and modify the haskell plugin to use an extended `wordPattern` like the one I linked to you could at least have this working locally for now. It should be enough to just fork the repo for the haskell plugin, run `npm install` in the directory, make the change (and run the build task with F5 or the command palette at least once), and then symlink it into `~/.vscode/extensions` with the other extensions. It doesn't need to have a special directory name or anything.

**Closed** 2016-11-11 03:57 UTC

**Comment by freebroccolo** [comment] 2016-11-11 03:58
I just uploaded a new version which should no longer leave the leading `\` in the haskell mode.

**Comment by freebroccolo** [comment] 2016-11-11 04:17
Looks like there's still an issue in one of the cases. Should be fixed shortly.

**Comment by scott-fleischman** [comment] 2016-11-11 06:37
Thanks!
